name: Paths Filter

on:
  workflow_call:
    outputs:
      application-relevant-files-changed:
        description: 'Whether application-relevant files were changed'
        value: ${{ jobs.paths-filter.outputs.application-relevant-files-changed }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      application-relevant-files-changed: ${{ steps.filter.outputs.application-relevant-files }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Filter Paths
      id: filter
      uses: dorny/paths-filter@v4.0.1  # Pinned to a specific version to avoid breaking changes.
      with:
        # Detect changes to `./src` code files, unit tests, dependencies, the (building of the) container image, and
        # the CI/CD GitHub Actions workflows.
        filters: |
          application-relevant-files:
            - 'src/**'
            - 'tests/**/*.py'
            - 'pyproject.toml'
            - 'uv.lock'
            - 'Dockerfile'
            - '.dockerignore'
            - '.github/workflows/**'
